// examples/components-bundle-test/src/App.tsx
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import './App.css';
import { LiveKitRoom } from '@livekit/components-react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <LiveKitRoom serverUrl="wss://encom.livekit.cloud" token="devtoken"></LiveKitRoom>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
    </div>
  );
}

export default App;

// packages/solid/src/App.tsx
import type { Component } from 'solid-js';
import logo from './logo.svg';
import styles from './App.module.css';
import './components';

const App: Component = () => {
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <livekit-room connect="true" url="test" token="none">
          <div>
            <div>
              <livekit-participant />
            </div>
          </div>
        </livekit-room>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
      </header>
    </div>
  );
};

export default App;
